version: '3.8'

services:
  node-app:
    container_name: frontend
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    env_file:
      ../.env
    ports:
      - "5173:5173"

    volumes:
      - ../frontend:/app

