version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - /mnt/wsl/minio/data:/data
      - /mnt/wsl/minio/config:/root/.minio
    command: server /data --console-address ":9090"
