version: '3.8'

services:
  flask-app:
    container_name: zarea
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    env_file:
      ../.env
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

    volumes:
      - ../backend:/app

