version: '3.8'

services:
  flask-app:
    container_name: backend
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    command: poetry run gunicorn -c backend/wsgi.py
    env_file:
      ../.env

    volumes:
      - ../backend:/app/backend
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - flask-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
