version: '3.8'

services:
  flask-app:
    container_name: zarea
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    env_file:
      ../.env
    ports:
      - "5000:5000"

    volumes:
      - ../backend:/app/backend

